// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/meta/Lexer.flex

package meta;

import static meta.Tokens.*;
import java.util.HashMap;
import java.util.Map;


@SuppressWarnings("fallthrough")
class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int BLOCK_COMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\1\u0400\266\u0200\10\u0500\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\1\1\5"+
    "\1\6\1\7\1\0\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\7\24"+
    "\2\25\1\26\1\27\1\30\1\31\1\32\1\26\1\33"+
    "\4\34\1\35\1\36\5\37\1\40\13\37\1\41\2\37"+
    "\1\26\1\42\1\26\1\43\1\37\1\0\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\1\53\1\54\1\37"+
    "\1\55\1\56\1\57\1\60\1\61\1\62\1\37\1\63"+
    "\1\64\1\65\1\66\1\67\1\70\1\71\1\72\1\73"+
    "\1\74\1\75\1\76\1\26\2\0\1\77\3\0\1\3"+
    "\7\0\1\77\1\0\2\77\14\0\1\77\3\0\7\77"+
    "\1\0\2\77\2\0\7\77\1\0\2\77\2\0\2\77"+
    "\1\0\33\77\1\0\31\77\1\100\5\77\1\0\10\77"+
    "\122\0\2\77\14\0\2\77\26\0\1\77\4\0\2\77"+
    "\23\0\1\77\u018b\0\1\77\1\0\3\77\3\0\1\77"+
    "\1\0\2\3\202\0\1\77\165\0\1\77\335\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\5\1\1\1\6"+
    "\1\7\1\1\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\7\1\16\2\17\1\7\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\7\17\25\1\26\1\7\1\27\1\1"+
    "\1\24\1\30\1\2\1\3\3\30\1\12\20\30\1\31"+
    "\1\32\5\0\1\33\1\34\1\0\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\3\50\1\51\1\52\1\53\6\25\1\54\5\25\1\55"+
    "\14\25\1\56\1\57\1\0\4\30\2\60\1\61\1\44"+
    "\6\30\1\54\5\30\1\55\14\30\5\0\1\62\1\63"+
    "\1\0\1\63\1\64\13\25\1\65\1\66\21\25\1\57"+
    "\15\30\1\65\1\66\21\30\5\0\1\63\1\67\1\25"+
    "\1\70\1\71\4\25\1\72\2\25\1\73\1\74\13\25"+
    "\1\75\3\25\2\30\1\67\1\30\1\70\1\71\4\30"+
    "\1\72\2\30\1\73\1\74\13\30\1\75\3\30\4\0"+
    "\1\76\1\77\5\25\1\100\6\25\1\101\1\102\2\30"+
    "\1\76\1\77\5\30\1\100\6\30\1\101\1\102\1\0"+
    "\1\103\2\0\3\25\1\104\1\105\5\30\1\104\1\105"+
    "\3\0\1\25\1\106\1\25\3\30\1\106\1\30\1\0"+
    "\1\103\1\0\1\107\2\30\1\107\2\0\2\30\1\103"+
    "\2\0\3\30\2\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[381];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\101\0\202\0\303\0\202\0\u0104\0\u0145\0\u0186"+
    "\0\u01c7\0\u0208\0\u0249\0\202\0\202\0\u028a\0\u02cb\0\202"+
    "\0\u030c\0\u034d\0\u038e\0\u03cf\0\u0410\0\202\0\202\0\u0451"+
    "\0\u0492\0\u04d3\0\202\0\u0514\0\u01c7\0\u0555\0\u0596\0\u05d7"+
    "\0\u0618\0\u0659\0\u069a\0\u06db\0\u071c\0\u075d\0\u079e\0\u07df"+
    "\0\u0820\0\u0861\0\u08a2\0\u08e3\0\202\0\u0924\0\202\0\u0965"+
    "\0\u0965\0\u09a6\0\u09e7\0\u09a6\0\u0a28\0\u0a69\0\u0aaa\0\u0aeb"+
    "\0\u0b2c\0\u0b6d\0\u0bae\0\u0bef\0\u0c30\0\u0c71\0\u0cb2\0\u0cf3"+
    "\0\u0d34\0\u0d75\0\u0db6\0\u0df7\0\u0e38\0\u0e79\0\u0eba\0\u0efb"+
    "\0\202\0\202\0\u0f3c\0\u0f7d\0\u0fbe\0\u0fff\0\u1040\0\202"+
    "\0\u1081\0\u10c2\0\202\0\202\0\202\0\202\0\202\0\u034d"+
    "\0\202\0\u1103\0\202\0\u1144\0\u1185\0\u11c6\0\u1207\0\u1248"+
    "\0\202\0\202\0\202\0\u1289\0\u12ca\0\u130b\0\u134c\0\u138d"+
    "\0\u13ce\0\u140f\0\u1450\0\u1491\0\u14d2\0\u1513\0\u1554\0\u0514"+
    "\0\u1595\0\u15d6\0\u1617\0\u1658\0\u1699\0\u16da\0\u171b\0\u175c"+
    "\0\u179d\0\u17de\0\u181f\0\u1860\0\202\0\u18a1\0\u0965\0\u18e2"+
    "\0\u1923\0\u1964\0\u19a5\0\202\0\u19e6\0\202\0\u1a27\0\u1a68"+
    "\0\u1aa9\0\u1aea\0\u1b2b\0\u1b6c\0\u1bad\0\u1bee\0\u1c2f\0\u1c70"+
    "\0\u1cb1\0\u1cf2\0\u1d33\0\u09a6\0\u1d74\0\u1db5\0\u1df6\0\u1e37"+
    "\0\u1e78\0\u1eb9\0\u1efa\0\u1f3b\0\u1f7c\0\u1fbd\0\u1ffe\0\u203f"+
    "\0\u2080\0\u20c1\0\u2102\0\u2143\0\u2184\0\202\0\u21c5\0\u2206"+
    "\0\u2247\0\u2288\0\u22c9\0\u230a\0\u234b\0\u238c\0\u23cd\0\u240e"+
    "\0\u244f\0\u2490\0\u24d1\0\u2512\0\u2553\0\u0514\0\u0514\0\u2594"+
    "\0\u25d5\0\u2616\0\u2657\0\u2698\0\u26d9\0\u271a\0\u275b\0\u279c"+
    "\0\u27dd\0\u281e\0\u285f\0\u28a0\0\u28e1\0\u2922\0\u2963\0\u29a4"+
    "\0\u29e5\0\u2a26\0\u2a67\0\u2aa8\0\u2ae9\0\u2b2a\0\u2b6b\0\u2bac"+
    "\0\u2bed\0\u2c2e\0\u2c6f\0\u2cb0\0\u2cf1\0\u2d32\0\u09a6\0\u09a6"+
    "\0\u2d73\0\u2db4\0\u2df5\0\u2e36\0\u2e77\0\u2eb8\0\u2ef9\0\u2f3a"+
    "\0\u2f7b\0\u2fbc\0\u2ffd\0\u303e\0\u307f\0\u30c0\0\u3101\0\u3142"+
    "\0\u3183\0\u31c4\0\u3205\0\u3246\0\u3287\0\u32c8\0\202\0\u0514"+
    "\0\u3309\0\u0514\0\u0514\0\u334a\0\u338b\0\u33cc\0\u340d\0\u0514"+
    "\0\u344e\0\u348f\0\u0514\0\u0514\0\u34d0\0\u3511\0\u3552\0\u3593"+
    "\0\u35d4\0\u3615\0\u3656\0\u3697\0\u36d8\0\u3719\0\u375a\0\u0514"+
    "\0\u379b\0\u37dc\0\u381d\0\u385e\0\u389f\0\u09a6\0\u38e0\0\u09a6"+
    "\0\u09a6\0\u3921\0\u3962\0\u39a3\0\u39e4\0\u09a6\0\u3a25\0\u3a66"+
    "\0\u09a6\0\u09a6\0\u3aa7\0\u3ae8\0\u3b29\0\u3b6a\0\u3bab\0\u3bec"+
    "\0\u3c2d\0\u3c6e\0\u3caf\0\u3cf0\0\u3d31\0\u09a6\0\u3d72\0\u3db3"+
    "\0\u3df4\0\u3e35\0\u3e76\0\u3eb7\0\u3ef8\0\u0514\0\u0514\0\u3f39"+
    "\0\u3f7a\0\u3fbb\0\u3ffc\0\u403d\0\u0514\0\u407e\0\u40bf\0\u4100"+
    "\0\u4141\0\u4182\0\u41c3\0\u0514\0\u0514\0\u4204\0\u4245\0\u09a6"+
    "\0\u09a6\0\u4286\0\u42c7\0\u4308\0\u4349\0\u438a\0\u09a6\0\u43cb"+
    "\0\u440c\0\u444d\0\u448e\0\u44cf\0\u4510\0\u09a6\0\u09a6\0\u4551"+
    "\0\202\0\u4592\0\u45d3\0\u4614\0\u4655\0\u4696\0\u0514\0\u0514"+
    "\0\u46d7\0\u4718\0\u4759\0\u479a\0\u47db\0\u09a6\0\u09a6\0\u481c"+
    "\0\u485d\0\u489e\0\u48df\0\u0514\0\u4920\0\u4961\0\u49a2\0\u49e3"+
    "\0\u09a6\0\u4a24\0\u4a65\0\u4aa6\0\u4ae7\0\u0514\0\u4b28\0\u4b69"+
    "\0\u09a6\0\u4baa\0\u4beb\0\u4c2c\0\u4c6d\0\u4cae\0\u4cef\0\u4d30"+
    "\0\u4d71\0\u4db2\0\u4df3\0\u4e34\0\u4e75";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[381];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\3\1\4\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\2\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\6\34\1\33\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\34\1\45\1\34"+
    "\1\46\4\34\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\3\34\1\55\1\56\1\57\1\60\1\61\1\62\1\63"+
    "\1\64\1\62\1\63\1\62\1\65\1\66\2\62\1\67"+
    "\2\62\1\70\4\62\1\71\21\62\1\72\1\73\1\74"+
    "\1\75\1\76\1\77\1\100\1\62\1\101\1\62\1\102"+
    "\4\62\1\103\1\104\1\105\1\106\1\107\1\110\10\62"+
    "\102\0\1\4\2\0\1\4\125\0\1\111\47\0\6\7"+
    "\1\112\33\7\1\113\36\7\47\0\1\114\1\115\3\0"+
    "\1\116\11\0\1\117\43\0\1\26\60\0\1\120\17\0"+
    "\1\26\47\0\12\121\1\0\27\121\1\122\36\121\31\0"+
    "\1\123\65\0\1\124\12\0\1\125\67\0\1\126\10\0"+
    "\1\127\1\26\71\0\3\130\70\0\1\131\4\0\1\132"+
    "\6\0\1\133\70\0\1\134\1\0\2\135\1\25\6\0"+
    "\1\136\1\137\3\136\1\140\2\0\4\136\1\137\20\136"+
    "\1\140\2\136\26\0\1\134\1\0\3\25\6\0\1\136"+
    "\1\137\4\136\2\0\4\136\1\137\23\136\35\0\1\35"+
    "\1\141\100\0\1\142\100\0\1\143\1\35\71\0\3\34"+
    "\6\0\6\34\2\0\30\34\30\0\3\34\6\0\6\34"+
    "\2\0\22\34\1\144\5\34\30\0\3\34\6\0\6\34"+
    "\2\0\17\34\1\145\10\34\30\0\3\34\6\0\6\34"+
    "\2\0\1\146\6\34\1\147\5\34\1\150\12\34\30\0"+
    "\3\34\6\0\6\34\2\0\4\34\1\151\10\34\1\152"+
    "\12\34\30\0\3\34\6\0\6\34\2\0\12\34\1\153"+
    "\1\34\1\154\10\34\1\155\2\34\30\0\3\34\6\0"+
    "\6\34\2\0\12\34\1\156\2\34\1\157\12\34\30\0"+
    "\3\34\6\0\6\34\2\0\15\34\1\144\12\34\30\0"+
    "\3\34\6\0\6\34\2\0\5\34\1\160\6\34\1\161"+
    "\13\34\30\0\3\34\6\0\6\34\2\0\15\34\1\162"+
    "\12\34\30\0\3\34\6\0\6\34\2\0\4\34\1\163"+
    "\23\34\30\0\3\34\6\0\6\34\2\0\7\34\1\164"+
    "\1\165\10\34\1\166\2\34\1\167\3\34\30\0\3\34"+
    "\6\0\6\34\2\0\26\34\1\170\1\34\30\0\3\34"+
    "\6\0\6\34\2\0\14\34\1\171\13\34\30\0\3\34"+
    "\6\0\6\34\2\0\15\34\1\172\12\34\30\0\3\34"+
    "\6\0\6\34\2\0\7\34\1\173\7\34\1\174\10\34"+
    "\36\0\1\26\43\0\1\175\37\0\6\176\2\0\30\176"+
    "\3\0\2\177\15\62\1\0\64\62\1\63\2\62\1\63"+
    "\10\62\1\0\63\62\6\65\1\62\6\65\1\7\24\65"+
    "\1\200\36\65\15\62\1\0\31\62\1\201\4\62\1\202"+
    "\41\62\1\121\24\62\1\203\36\62\15\204\1\205\4\204"+
    "\1\206\56\204\15\62\1\131\4\62\1\207\73\62\1\0"+
    "\50\62\1\210\27\62\1\0\45\62\1\211\32\62\1\0"+
    "\26\62\1\212\6\62\1\213\5\62\1\214\34\62\1\0"+
    "\32\62\1\215\10\62\1\216\34\62\1\0\40\62\1\217"+
    "\1\62\1\220\10\62\1\221\24\62\1\0\40\62\1\222"+
    "\2\62\1\223\34\62\1\0\43\62\1\210\34\62\1\0"+
    "\33\62\1\224\6\62\1\225\35\62\1\0\43\62\1\226"+
    "\34\62\1\0\32\62\1\227\45\62\1\0\35\62\1\230"+
    "\1\231\10\62\1\232\2\62\1\233\25\62\1\0\54\62"+
    "\1\234\23\62\1\0\42\62\1\235\35\62\1\0\43\62"+
    "\1\236\34\62\1\0\35\62\1\237\7\62\1\240\15\62"+
    "\2\7\3\0\74\7\50\0\1\241\110\0\1\242\71\0"+
    "\1\243\6\0\1\244\100\0\1\245\32\0\1\246\66\0"+
    "\2\121\3\0\74\121\2\132\3\0\74\132\23\0\3\247"+
    "\74\0\1\134\1\0\2\135\1\25\6\0\1\136\1\137"+
    "\4\136\2\0\4\136\1\137\23\136\41\0\6\136\2\0"+
    "\30\136\23\0\1\250\1\0\1\250\2\0\3\251\6\0"+
    "\6\136\2\0\30\136\30\0\3\252\6\0\3\140\3\136"+
    "\2\0\6\140\22\136\30\0\3\34\6\0\6\34\2\0"+
    "\21\34\1\253\6\34\30\0\3\34\6\0\6\34\2\0"+
    "\4\34\1\254\23\34\30\0\3\34\6\0\6\34\2\0"+
    "\20\34\1\255\7\34\30\0\3\34\6\0\6\34\2\0"+
    "\1\256\27\34\30\0\3\34\6\0\6\34\2\0\14\34"+
    "\1\257\13\34\30\0\3\34\6\0\6\34\2\0\5\34"+
    "\1\260\22\34\30\0\3\34\6\0\6\34\2\0\22\34"+
    "\1\261\5\34\30\0\3\34\6\0\6\34\2\0\20\34"+
    "\1\262\7\34\30\0\3\34\6\0\6\34\2\0\22\34"+
    "\1\263\5\34\30\0\3\34\6\0\6\34\2\0\21\34"+
    "\1\264\6\34\30\0\3\34\6\0\6\34\2\0\15\34"+
    "\1\265\12\34\30\0\3\34\6\0\6\34\2\0\17\34"+
    "\1\266\10\34\30\0\3\34\6\0\6\34\2\0\21\34"+
    "\1\267\6\34\30\0\3\34\6\0\6\34\2\0\14\34"+
    "\1\270\13\34\30\0\3\34\6\0\6\34\2\0\1\271"+
    "\5\34\1\272\12\34\1\273\6\34\30\0\3\34\6\0"+
    "\6\34\2\0\15\34\1\274\12\34\30\0\3\34\6\0"+
    "\6\34\2\0\6\34\1\275\20\34\1\276\30\0\3\34"+
    "\6\0\6\34\2\0\1\277\16\34\1\300\10\34\30\0"+
    "\3\34\6\0\6\34\2\0\10\34\1\301\17\34\30\0"+
    "\3\34\6\0\6\34\2\0\16\34\1\302\11\34\30\0"+
    "\3\34\6\0\6\34\2\0\10\34\1\303\7\34\1\304"+
    "\7\34\30\0\3\34\6\0\6\34\2\0\10\34\1\305"+
    "\1\34\1\306\15\34\30\0\3\34\6\0\6\34\2\0"+
    "\10\34\1\307\17\34\30\0\3\34\6\0\6\34\2\0"+
    "\10\34\1\310\17\34\41\0\6\176\2\0\30\176\3\0"+
    "\2\311\2\65\3\62\10\65\1\7\63\65\15\62\1\0"+
    "\32\62\1\312\45\62\1\0\42\62\1\313\35\62\1\121"+
    "\63\62\15\204\1\205\4\204\1\0\56\204\2\207\3\62"+
    "\10\207\1\132\63\207\15\62\1\0\47\62\1\314\30\62"+
    "\1\0\32\62\1\315\45\62\1\0\46\62\1\316\31\62"+
    "\1\0\26\62\1\317\51\62\1\0\42\62\1\320\35\62"+
    "\1\0\33\62\1\321\44\62\1\0\50\62\1\322\27\62"+
    "\1\0\46\62\1\323\31\62\1\0\50\62\1\324\27\62"+
    "\1\0\47\62\1\325\30\62\1\0\43\62\1\326\34\62"+
    "\1\0\45\62\1\327\32\62\1\0\47\62\1\330\30\62"+
    "\1\0\42\62\1\331\35\62\1\0\26\62\1\332\5\62"+
    "\1\333\12\62\1\334\30\62\1\0\43\62\1\335\34\62"+
    "\1\0\34\62\1\336\20\62\1\337\22\62\1\0\26\62"+
    "\1\340\16\62\1\341\32\62\1\0\36\62\1\342\41\62"+
    "\1\0\44\62\1\343\33\62\1\0\36\62\1\344\7\62"+
    "\1\345\31\62\1\0\36\62\1\346\1\62\1\347\37\62"+
    "\1\0\36\62\1\350\41\62\1\0\36\62\1\351\24\62"+
    "\51\0\1\352\76\0\1\353\100\0\1\354\10\0\1\245"+
    "\66\0\1\355\101\0\1\354\54\0\3\247\7\0\1\356"+
    "\1\357\1\0\1\357\7\0\1\356\1\357\4\0\1\357"+
    "\45\0\3\251\76\0\3\251\10\0\1\357\1\0\1\357"+
    "\10\0\1\357\4\0\1\357\45\0\3\252\6\0\3\252"+
    "\5\0\6\252\52\0\3\34\6\0\6\34\2\0\15\34"+
    "\1\360\12\34\30\0\3\34\6\0\6\34\2\0\1\361"+
    "\27\34\30\0\3\34\6\0\6\34\2\0\4\34\1\362"+
    "\23\34\30\0\3\34\6\0\6\34\2\0\17\34\1\363"+
    "\10\34\30\0\3\34\6\0\6\34\2\0\20\34\1\364"+
    "\1\365\6\34\30\0\3\34\6\0\6\34\2\0\1\366"+
    "\27\34\30\0\3\34\6\0\6\34\2\0\1\34\1\367"+
    "\26\34\30\0\3\34\6\0\6\34\2\0\4\34\1\370"+
    "\23\34\30\0\3\34\6\0\6\34\2\0\13\34\1\360"+
    "\14\34\30\0\3\34\6\0\6\34\2\0\4\34\1\371"+
    "\23\34\30\0\3\34\6\0\6\34\2\0\1\372\27\34"+
    "\30\0\3\34\6\0\6\34\2\0\6\34\1\373\21\34"+
    "\30\0\3\34\6\0\6\34\2\0\3\34\1\374\24\34"+
    "\30\0\3\34\6\0\6\34\2\0\10\34\1\375\17\34"+
    "\30\0\3\34\6\0\6\34\2\0\22\34\1\376\5\34"+
    "\30\0\3\34\6\0\6\34\2\0\17\34\1\377\10\34"+
    "\30\0\3\34\6\0\6\34\2\0\14\34\1\u0100\13\34"+
    "\30\0\3\34\6\0\6\34\2\0\4\34\1\u0101\23\34"+
    "\30\0\3\34\6\0\6\34\2\0\21\34\1\u0102\6\34"+
    "\30\0\3\34\6\0\6\34\2\0\22\34\1\u0103\5\34"+
    "\30\0\3\34\6\0\6\34\2\0\21\34\1\u0104\6\34"+
    "\30\0\3\34\6\0\6\34\2\0\4\34\1\u0105\23\34"+
    "\30\0\3\34\6\0\6\34\2\0\15\34\1\u0106\12\34"+
    "\30\0\3\34\6\0\6\34\2\0\10\34\1\u0107\17\34"+
    "\30\0\3\34\6\0\6\34\2\0\3\34\1\u0108\24\34"+
    "\30\0\3\34\6\0\6\34\2\0\1\u0109\27\34\30\0"+
    "\3\34\6\0\6\34\2\0\12\34\1\u010a\15\34\30\0"+
    "\3\34\6\0\6\34\2\0\21\34\1\u010b\6\34\104\0"+
    "\2\311\15\62\1\0\33\62\1\u010c\44\62\1\0\30\62"+
    "\1\u010d\47\62\1\0\43\62\1\u010e\34\62\1\0\26\62"+
    "\1\u010f\51\62\1\0\32\62\1\u0110\45\62\1\0\45\62"+
    "\1\u0111\32\62\1\0\46\62\1\u0112\1\u0113\30\62\1\0"+
    "\26\62\1\u0114\51\62\1\0\27\62\1\u0115\50\62\1\0"+
    "\32\62\1\u0116\45\62\1\0\41\62\1\u010e\36\62\1\0"+
    "\32\62\1\u0117\45\62\1\0\26\62\1\u0118\51\62\1\0"+
    "\34\62\1\u0119\43\62\1\0\31\62\1\u011a\46\62\1\0"+
    "\36\62\1\u011b\41\62\1\0\50\62\1\u011c\27\62\1\0"+
    "\45\62\1\u011d\32\62\1\0\42\62\1\u011e\35\62\1\0"+
    "\32\62\1\u011f\45\62\1\0\47\62\1\u0120\30\62\1\0"+
    "\50\62\1\u0121\27\62\1\0\47\62\1\u0122\30\62\1\0"+
    "\32\62\1\u0123\45\62\1\0\43\62\1\u0124\34\62\1\0"+
    "\36\62\1\u0125\41\62\1\0\31\62\1\u0126\46\62\1\0"+
    "\26\62\1\u0127\51\62\1\0\40\62\1\u0128\37\62\1\0"+
    "\47\62\1\u0129\13\62\54\0\1\u012a\100\0\1\u012b\74\0"+
    "\1\u012c\106\0\1\u012d\40\0\1\250\1\0\1\250\2\0"+
    "\3\251\76\0\3\34\6\0\6\34\2\0\11\34\1\u012e"+
    "\16\34\30\0\3\34\6\0\6\34\2\0\21\34\1\u012f"+
    "\6\34\30\0\3\34\6\0\6\34\2\0\10\34\1\u0130"+
    "\17\34\30\0\3\34\6\0\6\34\2\0\22\34\1\u0131"+
    "\5\34\30\0\3\34\6\0\6\34\2\0\12\34\1\u0132"+
    "\15\34\30\0\3\34\6\0\6\34\2\0\17\34\1\u0106"+
    "\10\34\30\0\3\34\6\0\6\34\2\0\21\34\1\360"+
    "\6\34\30\0\3\34\6\0\6\34\2\0\20\34\1\u0133"+
    "\7\34\30\0\3\34\6\0\6\34\2\0\17\34\1\u0134"+
    "\10\34\30\0\3\34\6\0\6\34\2\0\21\34\1\u0135"+
    "\6\34\30\0\3\34\6\0\6\34\2\0\4\34\1\u0136"+
    "\23\34\30\0\3\34\6\0\6\34\2\0\15\34\1\u0137"+
    "\12\34\30\0\3\34\6\0\6\34\2\0\10\34\1\u0138"+
    "\17\34\30\0\3\34\6\0\6\34\2\0\2\34\1\372"+
    "\25\34\30\0\3\34\6\0\6\34\2\0\2\34\1\u0139"+
    "\25\34\30\0\3\34\6\0\6\34\2\0\3\34\1\u013a"+
    "\24\34\30\0\3\34\6\0\6\34\2\0\14\34\1\360"+
    "\13\34\30\0\3\34\6\0\6\34\2\0\6\34\1\275"+
    "\21\34\30\0\3\34\6\0\6\34\2\0\21\34\1\u013b"+
    "\6\34\30\0\3\34\6\0\6\34\2\0\4\34\1\u013c"+
    "\23\34\30\0\3\34\6\0\6\34\2\0\4\34\1\u013d"+
    "\23\34\5\0\15\62\1\0\36\62\1\u013e\41\62\1\0"+
    "\40\62\1\u013f\37\62\1\0\37\62\1\u0140\40\62\1\0"+
    "\47\62\1\u0141\30\62\1\0\36\62\1\u0142\41\62\1\0"+
    "\50\62\1\u0143\27\62\1\0\40\62\1\u0144\37\62\1\0"+
    "\45\62\1\u0124\32\62\1\0\47\62\1\u010e\30\62\1\0"+
    "\46\62\1\u0145\31\62\1\0\45\62\1\u0146\32\62\1\0"+
    "\47\62\1\u0147\30\62\1\0\32\62\1\u0148\45\62\1\0"+
    "\43\62\1\u0149\34\62\1\0\36\62\1\u014a\41\62\1\0"+
    "\30\62\1\u0118\47\62\1\0\30\62\1\u014b\47\62\1\0"+
    "\31\62\1\u014c\46\62\1\0\42\62\1\u010e\35\62\1\0"+
    "\34\62\1\336\43\62\1\0\47\62\1\u014d\30\62\1\0"+
    "\32\62\1\u014e\45\62\1\0\32\62\1\u014f\30\62\60\0"+
    "\1\u0150\71\0\1\u0151\100\0\1\u0152\115\0\1\u0153\35\0"+
    "\3\34\6\0\6\34\2\0\14\34\1\u0154\13\34\30\0"+
    "\3\34\6\0\6\34\2\0\12\34\1\u0155\15\34\30\0"+
    "\3\34\6\0\6\34\2\0\4\34\1\360\23\34\30\0"+
    "\3\34\6\0\6\34\2\0\21\34\1\u0156\6\34\30\0"+
    "\3\34\6\0\6\34\2\0\14\34\1\u0157\13\34\30\0"+
    "\3\34\6\0\6\34\2\0\3\34\1\360\24\34\30\0"+
    "\3\34\6\0\6\34\2\0\5\34\1\360\22\34\30\0"+
    "\3\34\6\0\6\34\2\0\2\34\1\360\25\34\30\0"+
    "\3\34\6\0\6\34\2\0\7\34\1\u0158\20\34\30\0"+
    "\3\34\6\0\6\34\2\0\4\34\1\u0137\23\34\30\0"+
    "\3\34\6\0\6\34\2\0\10\34\1\367\17\34\5\0"+
    "\15\62\1\0\42\62\1\u0159\35\62\1\0\50\62\1\u015a"+
    "\27\62\1\0\42\62\1\u015b\35\62\1\0\40\62\1\u015c"+
    "\37\62\1\0\32\62\1\u010e\45\62\1\0\47\62\1\u015d"+
    "\30\62\1\0\42\62\1\u015e\35\62\1\0\31\62\1\u010e"+
    "\46\62\1\0\33\62\1\u010e\44\62\1\0\30\62\1\u010e"+
    "\47\62\1\0\35\62\1\u015f\42\62\1\0\32\62\1\u0149"+
    "\45\62\1\0\36\62\1\u0115\24\62\50\0\1\u0160\31\0"+
    "\1\u0161\146\0\1\u0162\54\0\3\34\6\0\6\34\2\0"+
    "\22\34\1\u0163\5\34\30\0\3\34\6\0\6\34\2\0"+
    "\21\34\1\u0164\6\34\30\0\3\34\6\0\6\34\2\0"+
    "\4\34\1\u0165\23\34\5\0\15\62\1\0\32\62\1\u0166"+
    "\45\62\1\0\31\62\1\u0167\46\62\1\0\50\62\1\u0168"+
    "\27\62\1\0\47\62\1\u0169\30\62\1\0\32\62\1\u016a"+
    "\30\62\1\0\1\u016b\100\0\1\u0161\32\0\6\u016c\2\0"+
    "\30\u016c\55\0\1\u016d\53\0\3\34\6\0\6\34\2\0"+
    "\4\34\1\u016e\23\34\30\0\3\34\6\0\6\34\2\0"+
    "\17\34\1\360\10\34\5\0\1\62\1\u016f\13\62\1\0"+
    "\100\62\1\0\32\62\1\u0170\45\62\1\0\32\62\1\u0171"+
    "\45\62\1\0\45\62\1\u010e\15\62\1\0\1\u016b\32\0"+
    "\6\u0172\2\0\30\u0172\41\0\6\u016c\2\0\30\u016c\6\0"+
    "\1\u0173\77\0\1\62\1\u016f\13\62\1\0\16\62\6\u0174"+
    "\2\62\30\u0174\6\62\1\u0175\13\62\1\0\63\62\1\0"+
    "\1\u0176\32\0\6\u0172\2\0\30\u0172\6\0\1\u0173\4\0"+
    "\1\u0177\21\0\1\u0178\50\0\1\62\1\u0179\13\62\1\0"+
    "\16\62\6\u0174\2\62\30\u0174\6\62\1\u0175\4\62\1\u017a"+
    "\6\62\1\0\12\62\1\u017b\50\62\2\u0176\3\0\74\u0176"+
    "\6\u017c\1\0\72\u017c\32\u017d\1\0\46\u017d\2\u0179\3\62"+
    "\10\u0179\1\u0176\63\u0179\6\u017a\1\62\6\u017a\1\u017c\63\u017a"+
    "\15\u017b\1\u017d\14\u017b\1\62\46\u017b\6\u017c\1\u0151\72\u017c"+
    "\32\u017d\1\u0151\46\u017d";

  private static int [] zzUnpacktrans() {
    int [] result = new int[20150];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\6\1\2\11\2\1\1\11"+
    "\5\1\2\11\3\1\1\11\21\1\1\11\1\1\1\11"+
    "\31\1\2\11\5\0\1\11\1\1\1\0\5\11\1\1"+
    "\1\11\1\1\1\11\5\1\3\11\31\1\1\11\1\1"+
    "\1\0\4\1\1\11\1\1\1\11\32\1\5\0\1\11"+
    "\1\1\1\0\101\1\5\0\1\11\72\1\4\0\42\1"+
    "\1\0\1\11\2\0\14\1\3\0\10\1\1\0\1\1"+
    "\1\0\4\1\2\0\3\1\2\0\3\1\2\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[381];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;
    public int lineNumber = 1; // Variable para contar el número de líneas
    private Map<String, Map<Integer, Integer>> tokenCountMap = new HashMap<>(); // Mapa para contar tokens por línea
    private boolean insideBlockComment = false;
    private boolean insideString = false; // Nueva bandera para strings no cerrados

    // Método para hacer seguimiento de tokens repetidos en una misma línea 
    private void trackToken(String lexeme) {
        if (!tokenCountMap.containsKey(lexeme)) {
            tokenCountMap.put(lexeme, new HashMap<>());
        }
        Map<Integer, Integer> lineCountMap = tokenCountMap.get(lexeme);
        
        // Incrementamos el conteo para la línea actual
        lineCountMap.put(lineNumber, lineCountMap.getOrDefault(lineNumber, 0) + 1);
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Tokens yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case BLOCK_COMMENT: {
              System.err.println("Error: Comentario de bloque no cerrado en línea " + lineNumber);
    return COMENTARIO_NO_FINALIZADO;
            }  // fall though
            case 382: break;
            default:
        return null;
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { lexeme = yytext();
    System.err.println("Error: Carácter no definido encontrado en línea " + lineNumber + ": " + yytext());
    return CARACTER_NO_DEFINIDO;
            }
          // fall through
          case 72: break;
          case 2:
            { /* Ignorar espacios en blanco */
            }
          // fall through
          case 73: break;
          case 3:
            { lineNumber++;
            }
          // fall through
          case 74: break;
          case 4:
            { return Not;
            }
          // fall through
          case 75: break;
          case 5:
            { lexeme = yytext(); 
    System.err.println("Error: String no cerrado en línea " + lineNumber);
    return STRING_NO_CERRADO;
            }
          // fall through
          case 76: break;
          case 6:
            { return Modulo;
            }
          // fall through
          case 77: break;
          case 7:
            { return Operador;
            }
          // fall through
          case 78: break;
          case 8:
            { return ParentesisA;
            }
          // fall through
          case 79: break;
          case 9:
            { return ParentesisC;
            }
          // fall through
          case 80: break;
          case 10:
            { return Multiplicacion;
            }
          // fall through
          case 81: break;
          case 11:
            { return Suma;
            }
          // fall through
          case 82: break;
          case 12:
            { return Coma;
            }
          // fall through
          case 83: break;
          case 13:
            { return Resta;
            }
          // fall through
          case 84: break;
          case 14:
            { return Division;
            }
          // fall through
          case 85: break;
          case 15:
            { return Decimal;
            }
          // fall through
          case 86: break;
          case 16:
            { return PuntoComa;
            }
          // fall through
          case 87: break;
          case 17:
            { return Menor;
            }
          // fall through
          case 88: break;
          case 18:
            { return Asignacion;
            }
          // fall through
          case 89: break;
          case 19:
            { return Mayor;
            }
          // fall through
          case 90: break;
          case 20:
            { return CARACTER_NO_DEFINIDO;
            }
          // fall through
          case 91: break;
          case 21:
            { lexeme = yytext(); 
    trackToken(lexeme); 
    return Identificador;
            }
          // fall through
          case 92: break;
          case 22:
            { return LlaveA;
            }
          // fall through
          case 93: break;
          case 23:
            { return LlaveC;
            }
          // fall through
          case 94: break;
          case 24:
            { /* Consume todos los caracteres excepto '*' */
            }
          // fall through
          case 95: break;
          case 25:
            { return Desigualdad;
            }
          // fall through
          case 96: break;
          case 26:
            { lexeme = yytext(); 
    if (lexeme.contains("\n")) {
        System.err.println("Error: String de varias lineas en línea " + lineNumber);
        return STRING_MULTILINEA_CERRADO;
    }
    insideString = false; // El string está cerrado correctamente
    trackToken(lexeme); 
    return Literal;
            }
          // fall through
          case 97: break;
          case 27:
            { return And;
            }
          // fall through
          case 98: break;
          case 28:
            { lexeme = yytext(); 
    System.err.println("Error: Carácter no cerrado en línea " + lineNumber);
    return CHAR_NO_CERRADO;
            }
          // fall through
          case 99: break;
          case 29:
            { return AsignacionMultiplicacion;
            }
          // fall through
          case 100: break;
          case 30:
            { return Incremento;
            }
          // fall through
          case 101: break;
          case 31:
            { return AsignacionSuma;
            }
          // fall through
          case 102: break;
          case 32:
            { return Decremento;
            }
          // fall through
          case 103: break;
          case 33:
            { return AsignacionResta;
            }
          // fall through
          case 104: break;
          case 34:
            { lexeme = yytext();
    System.err.println("Error: Número incompleto (sin dígito antes del punto decimal) en línea " + lineNumber);
    return NUMERO_INCOMPLETO;
            }
          // fall through
          case 105: break;
          case 35:
            { if (!insideString) {
        yybegin(BLOCK_COMMENT);
    } else {
        // Es parte de un string, no hacemos nada
    }
            }
          // fall through
          case 106: break;
          case 36:
            { if (!insideString) {
        // Comentario de línea, ignorar
    } else {
        // Es parte de un string, no hacemos nada
    }
            }
          // fall through
          case 107: break;
          case 37:
            { return AsignacionDivision;
            }
          // fall through
          case 108: break;
          case 38:
            { lexeme = yytext();
    System.err.println("Error: Número incompleto (sin dígito después del punto decimal) en línea " + lineNumber);
    return NUMERO_INCOMPLETO;
            }
          // fall through
          case 109: break;
          case 39:
            { return Octal;
            }
          // fall through
          case 110: break;
          case 40:
            { lexeme = yytext();
    System.err.println("Error: Identificador inválido que comienza con un número en línea " + lineNumber);
    return IDENTIFICADOR_INVALIDO;
            }
          // fall through
          case 111: break;
          case 41:
            { return MenorIgual;
            }
          // fall through
          case 112: break;
          case 42:
            { return Igualdad;
            }
          // fall through
          case 113: break;
          case 43:
            { return MayorIgual;
            }
          // fall through
          case 114: break;
          case 44:
            { return Do;
            }
          // fall through
          case 115: break;
          case 45:
            { return If;
            }
          // fall through
          case 116: break;
          case 46:
            { return Or;
            }
          // fall through
          case 117: break;
          case 47:
            { lexeme = yytext();
    System.err.println("Error: Identificador contiene caracteres no válidos en línea " + lineNumber + ": " + lexeme);
    return IDENTIFICADOR_NO_VALIDO;
            }
          // fall through
          case 118: break;
          case 48:
            { /* Consume secuencias de '*' no seguidas por '/' */
            }
          // fall through
          case 119: break;
          case 49:
            { yybegin(YYINITIAL);
            }
          // fall through
          case 120: break;
          case 50:
            { lexeme = yytext(); 
    trackToken(lexeme); 
    return Literal;
            }
          // fall through
          case 121: break;
          case 51:
            { return Flotante;
            }
          // fall through
          case 122: break;
          case 52:
            { return Hexadecimal;
            }
          // fall through
          case 123: break;
          case 53:
            { return For;
            }
          // fall through
          case 124: break;
          case 54:
            { return Int;
            }
          // fall through
          case 125: break;
          case 55:
            { return Reservada;
            }
          // fall through
          case 126: break;
          case 56:
            { return Case;
            }
          // fall through
          case 127: break;
          case 57:
            { return Char;
            }
          // fall through
          case 128: break;
          case 58:
            { return Else;
            }
          // fall through
          case 129: break;
          case 59:
            { return Long;
            }
          // fall through
          case 130: break;
          case 60:
            { return Read;
            }
          // fall through
          case 131: break;
          case 61:
            { return Void;
            }
          // fall through
          case 132: break;
          case 62:
            { return Break;
            }
          // fall through
          case 133: break;
          case 63:
            { return Const;
            }
          // fall through
          case 134: break;
          case 64:
            { return Short;
            }
          // fall through
          case 135: break;
          case 65:
            { return While;
            }
          // fall through
          case 136: break;
          case 66:
            { return Write;
            }
          // fall through
          case 137: break;
          case 67:
            { lexeme = yytext(); 
    return Preprocesador;
            }
          // fall through
          case 138: break;
          case 68:
            { return Return;
            }
          // fall through
          case 139: break;
          case 69:
            { return Switch;
            }
          // fall through
          case 140: break;
          case 70:
            { return Default;
            }
          // fall through
          case 141: break;
          case 71:
            { return Continue;
            }
          // fall through
          case 142: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
