
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package meta;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Espacios = 60;
  public static final int Or = 27;
  public static final int IDENTIFICADOR_INVALIDO = 63;
  public static final int Desigualdad = 26;
  public static final int Incremento = 19;
  public static final int PuntoComa = 45;
  public static final int Literal = 57;
  public static final int Hexadecimal = 54;
  public static final int CARACTER_NO_DEFINIDO = 48;
  public static final int If = 11;
  public static final int Void = 17;
  public static final int LlaveC = 39;
  public static final int IDENTIFICADOR_NO_VALIDO = 64;
  public static final int AsignacionResta = 41;
  public static final int Decremento = 20;
  public static final int LlaveA = 38;
  public static final int Default = 7;
  public static final int Operador = 61;
  public static final int Menor = 25;
  public static final int Else = 9;
  public static final int Read = 58;
  public static final int Break = 2;
  public static final int Asignacion = 30;
  public static final int Mayor = 23;
  public static final int Long = 13;
  public static final int Return = 14;
  public static final int While = 18;
  public static final int Division = 34;
  public static final int Int = 12;
  public static final int Flotante = 55;
  public static final int CHAR_NO_CERRADO = 50;
  public static final int Modulo = 35;
  public static final int For = 10;
  public static final int EOF = 0;
  public static final int DosPuntos = 46;
  public static final int Not = 29;
  public static final int And = 28;
  public static final int error = 1;
  public static final int Switch = 16;
  public static final int ComaSimple = 44;
  public static final int Reservada = 65;
  public static final int Char = 4;
  public static final int Do = 8;
  public static final int COMENTARIO_NO_FINALIZADO = 47;
  public static final int Continue = 6;
  public static final int STRING_NO_CERRADO = 49;
  public static final int Case = 3;
  public static final int MenorIgual = 24;
  public static final int Short = 15;
  public static final int Const = 5;
  public static final int NUMERO_INCOMPLETO = 62;
  public static final int AsignacionMultiplicacion = 42;
  public static final int AsignacionDivision = 43;
  public static final int Identificador = 56;
  public static final int Octal = 53;
  public static final int Preprocesador = 51;
  public static final int Resta = 32;
  public static final int MayorIgual = 22;
  public static final int AsignacionSuma = 40;
  public static final int Igualdad = 21;
  public static final int ParentesisC = 37;
  public static final int Decimal = 52;
  public static final int Multiplicacion = 33;
  public static final int ParentesisA = 36;
  public static final int Write = 59;
  public static final int Suma = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Break",
  "Case",
  "Char",
  "Const",
  "Continue",
  "Default",
  "Do",
  "Else",
  "For",
  "If",
  "Int",
  "Long",
  "Return",
  "Short",
  "Switch",
  "Void",
  "While",
  "Incremento",
  "Decremento",
  "Igualdad",
  "MayorIgual",
  "Mayor",
  "MenorIgual",
  "Menor",
  "Desigualdad",
  "Or",
  "And",
  "Not",
  "Asignacion",
  "Suma",
  "Resta",
  "Multiplicacion",
  "Division",
  "Modulo",
  "ParentesisA",
  "ParentesisC",
  "LlaveA",
  "LlaveC",
  "AsignacionSuma",
  "AsignacionResta",
  "AsignacionMultiplicacion",
  "AsignacionDivision",
  "ComaSimple",
  "PuntoComa",
  "DosPuntos",
  "COMENTARIO_NO_FINALIZADO",
  "CARACTER_NO_DEFINIDO",
  "STRING_NO_CERRADO",
  "CHAR_NO_CERRADO",
  "Preprocesador",
  "Decimal",
  "Octal",
  "Hexadecimal",
  "Flotante",
  "Identificador",
  "Literal",
  "Read",
  "Write",
  "Espacios",
  "Operador",
  "NUMERO_INCOMPLETO",
  "IDENTIFICADOR_INVALIDO",
  "IDENTIFICADOR_NO_VALIDO",
  "Reservada"
  };
}

